export const initialRoles = [
  { name: 'Gameplay Programmer', description: 'Implements core player mechanics, combat, movement, and gameplay systems.' },
  { name: 'Systems Programmer', description: 'Engineers low-level architecture, memory management, and core framework systems.' },
  { name: 'Engine Programmer', description: 'Customizes and extends game engine internals, rendering pipelines, and subsystems.' },
  { name: 'Graphics Programmer', description: 'Develops shaders, visual effects pipelines, lighting, and rendering algorithms.' },
  { name: 'Network Programmer', description: 'Architects multiplayer networking, client-server synchronization, and latency mitigation.' },
  { name: 'AI Programmer', description: 'Implements non-player character behavior, decision trees, pathfinding, and state machines.' },
  { name: 'Technical Artist', description: 'Bridges art and code by building shaders, rigging, visual pipelines, and optimization tools.' },
  { name: '3D Artist', description: 'Creates 3D hard-surface and organic models, textures, and assets.' },
  { name: '2D Artist', description: 'Designs concept art, UI art, textures, and 2D visual elements.' },
  { name: 'Environment Artist', description: 'Builds 3D environments, set-dressing, world materials, and level art.' },
  { name: 'Character Artist', description: 'Sculpts, models, and textures high-fidelity character models and creatures.' },
  { name: 'Animator', description: 'Animates 3D and 2D characters, keyframe motion, and motion capture data.' },
  { name: 'Game Designer', description: 'Designs game systems, rules, combat balance, and overall gameplay feel.' },
  { name: 'Level Designer', description: 'Layouts game levels, spatial pacing, encounter design, and level scripting.' },
  { name: 'Narrative Designer', description: 'Writes lore, branching dialogue systems, quest design, and story structure.' },
  { name: 'Technical Designer', description: 'Scripting-focused designer implementing prototypes, tools, and visual scripting.' },
  { name: 'Sound Designer', description: 'Creates sound effects, foley, audio implementation, and spatial audio routing.' },
  { name: 'Composer', description: 'Composes dynamic soundtrack, adaptive music tracks, and musical themes.' },
  { name: 'Producer', description: 'Manages production timelines, sprint planning, studio resources, and milestones.' },
  { name: 'QA Tester', description: 'Tests builds for functional bugs, regression, performance bottlenecks, and compliance.' },
];
