export const initialSkills = [
  { name: 'C++', description: 'High-performance systems language widely used in AAA game development.' },
  { name: 'C#', description: 'Primary programming language for Unity game engine and tooling.' },
  { name: 'Python', description: 'Scripting language used for pipeline automation, DCC plugins, and AI tools.' },
  { name: 'Gameplay Programming', description: 'Implementing game rules, player abilities, and interactive features.' },
  { name: 'Gameplay Systems', description: 'Architecting modular inventory, quest, stat, and dialogue frameworks.' },
  { name: 'Game AI', description: 'Designing decision trees, behavior trees, and intelligent agent behaviors.' },
  { name: 'Multiplayer Networking', description: 'Client prediction, server reconciliation, RPCs, and state replication.' },
  { name: 'Shader Programming', description: 'Writing HLSL, GLSL, Shader Graph, or Material Graph shaders.' },
  { name: 'Graphics Programming', description: 'Working with Vulkan, DirectX, Metal, OpenGL, and render graphs.' },
  { name: 'Physics Programming', description: 'Integrating PhysX, Chaos, Havok, or custom physics solvers.' },
  { name: 'Procedural Generation', description: 'Building PCG algorithms for dungeon generation, terrain, and foliage.' },
  { name: 'Animation Programming', description: 'State machines, motion matching, inverse kinematics, and blend trees.' },
  { name: 'Technical Art', description: 'Optimizing draw calls, mesh topology, materials, and pipeline tools.' },
  { name: '3D Modeling', description: 'Polygon modeling, subdivision surface, and hard-surface techniques.' },
  { name: 'Digital Sculpting', description: 'High-poly organic sculpting in ZBrush or Mudbox.' },
  { name: 'Texturing & PBR Workflows', description: 'Physically based rendering texture creation and PBR maps.' },
  { name: 'Rigging & Skinning', description: 'Creating bone hierarchies, skin weights, and control rigs.' },
  { name: 'Level Design', description: 'Blockout composition, flow design, lighting setup, and encounter pacing.' },
  { name: 'Sound Design', description: 'Foley recording, sound synthesis, audio editing, and soundscape design.' },
  { name: 'Agile & Sprint Planning', description: 'Iterative game production, Scrum sprints, and backlog prioritization.' },
];
